AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'test/fixtures/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'config.ru'
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/controllers/projects_controller.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/controllers/projects_controller.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false